# Generated by Django 2.0.6 on 2019-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0002_employeelist_headpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='headpic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
